### ISSUE TITLE
Why SDL_SetKeymap is not in public API?

### ISSUE THREAD

**Issue by mittorn** [spurious/SDL-mirror#3]
First, SDL makes translate from native keycodes to SDL scancodes
After that, sdl scancodes are translated to sdl keycodes.
And finally in sdl application i must translate them to my keycodes.
Why i cannot ajust keycodes tables from application to prevent last translation? What purpose of internal SDL keymap?

**Comment by okuoku** [comment]
Hi @mittorn , here is just a mirror of the SDL hg repository.

Generic SDL suggestions should go to libsdl ML( https://www.libsdl.org/mailing-list.php ) or forums ( http://forums.libsdl.org/ ).
